version: '3.8'

services:

  db:
    image: postgres:15.2
    container_name: grouptask
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=grouptask
      - POSTGRES_USER=sebastian
      - POSTGRES_PASSWORD=grouptask
    ports:
      - "5432:5432"